<br>
<br>
<h1 style="text-align: center">ELIMINAR CUENTA DE PROVEEDOR</h1>     

<fieldset>
        <legend style="font-size: 15px; margin-bottom: -10px;margin-left: 8px ;width: auto;">Eliminar Proveedor</legend>
        <br><br>
    <table class="general" summary="Proveedores" style="width:50%">
    <caption>¿Seguro que desea eliminar?</caption>
    <tbody>
    <tr>
        <th style="width: 200px" align="center">Código Banco:</th>
        <td align="center"><?php echo $this->escape($this->proveedores->codigo_banco); ?></td>
    </tr>
    <tr>
        <th align="center">Banco:</th>
        <td align="center"><?php echo $this->escape($this->proveedores->banco); ?></td>
    </tr>
    <tr>
        <th align="center">Número de Cuenta:</th>
        <td align="center"><?php echo $this->escape($this->proveedores->numcuenta); ?></td>   
    </tr>
    <tr>
        <th align="center">Estado de la Cuenta:</th>
        <td align="center"><?php echo $this->escape($this->proveedores->estado); ?></td>
    </tr>
    </table>
    <p align="center">
        <a class="button" href="<?php echo $this->url(array('module' => 'default', 'controller' => 'proveedores', 'action' => 'detalle', 'page' => $this->page), null, true); ?>"><?php echo $this->img('ico_volver.png'); ?> Volver</a>
        <a class="button" href="<?php echo $this->url(array('module' => 'default', 'controller' => 'proveedores', 'action' => 'eliminarcuenta', 'confirmar' => 'S', 'page' => $this->page, 'numcuenta' => $this->proveedores->numcuenta), null, true); ?>"><?php echo $this->img('ico_eliminar.png'); ?> Eliminar</a>
    </p>
</fieldset>