<script language="javascript">
    function getDatosBanco(){
        var txtCodigo = $('#cod');
        var ruta = txtCodigo.attr('url');
        $('#codtxt').val('');
        $('#banco').val('');
        $('#bcv').val('');
        $('#numcuenta').val('');

        $.ajax({
            type: 'GET',
            url: ruta + '/bancos/' + txtCodigo.val(),
            dataType: 'json',
            async: true,
            beforeSend: function () { $("#modal").show(); },
            complete: function () { $("#modal").hide(); }, 
            success: function (bancos) {
                if(bancos){               
                    $('#codtxt').val(bancos.codigo);
                    $('#banco').val(bancos.nombre_banco);
                    $('#bcv').val(bancos.bcv);
                    $('#numcuenta').val(bancos.bcv);
                }
            }
        });
    }
</script>


<style>
    #tblProveedores td {
        text-align: center;
    }
    
    #modal {
    display: none;
    position: absolute;
    top: 45%;
    left: 45%;
    width: 64px;
    height: 64px;
    padding: 2.5% 2.5%;
    border: 3px solid #ababab;
    box-shadow:1px 1px 10px #ababab;
    border-radius:20px;
    background-color: white;
    z-index: 1002;
    text-align:center;
    overflow: auto;
    }
</style>

<div id="modal">
    <?php echo $this->img('spinner.gif', array('alt' => 'spinner.gif', 'width' => '64', 'height' => '64')); ?>
</div>


<br>
<h1 style="text-align: center">REGISTRO DE UN NUEVO PROVEEDOR</h1>

<!-- FORMULARIO DE REGISTRO DE PROVEEDORES -->

<?php echo $this->formulario->renderForm(false); ?>

<fieldset><br><br>          
    <table class="general" summary="Datos Del Proveedor" style="width:30%">
        <legend style="font-size: 15px; margin-bottom: 0px;margin-left: 8px ;width: auto;">Datos de Proveedor</legend>
     <!--   <tbody>  
            <tr>
                <th style="width: 30%">R.I.F/C.I:</th>
                <td style="width: 2%"><?php
                    echo $this->formulario->getElement(Application_Form_Proveedores::E_LETRA)->renderViewHelper(),
                         $this->formulario->getElement(Application_Form_Proveedores::E_LETRA)->renderDescription(),
                         $this->formulario->getElement(Application_Form_Proveedores::E_LETRA)->renderErrors();
                         ?>
                </td>
                <td style="width: 50%"><?php
                    echo $this->formulario->getElement(Application_Form_Proveedores::E_RIF)->renderViewHelper(),
                         $this->formulario->getElement(Application_Form_Proveedores::E_RIF)->renderDescription(),
                         $this->formulario->getElement(Application_Form_Proveedores::E_RIF)->renderErrors();
                             ?>
                </td>
            </tr>
        </tbody>-->
    </table>
    
    <table class="general" summary="Datos Del Proveedor" style="width:55%; border-bottom: 1">
        <tbody>
            <tr>
             <th>Razón Social:</th>
                <td><?php
                    echo $this->formulario->getElement(Application_Form_Proveedores::E_RAZON)->renderViewHelper(),
                         $this->formulario->getElement(Application_Form_Proveedores::E_RAZON)->renderDescription(),
                         $this->formulario->getElement(Application_Form_Proveedores::E_RAZON)->renderErrors();
                    ?>
                
            
                <th>R.I.F/C.I:</th>
                <td><?php
                    echo $this->formulario->getElement(Application_Form_Proveedores::E_LETRA)->renderViewHelper(),
                         $this->formulario->getElement(Application_Form_Proveedores::E_LETRA)->renderDescription(),
                         $this->formulario->getElement(Application_Form_Proveedores::E_LETRA)->renderErrors();
                         ?>
                
                <?php
                    echo $this->formulario->getElement(Application_Form_Proveedores::E_RIF)->renderViewHelper(),
                         $this->formulario->getElement(Application_Form_Proveedores::E_RIF)->renderDescription(),
                         $this->formulario->getElement(Application_Form_Proveedores::E_RIF)->renderErrors();
                             ?>
                </td>
            </tr>
            <tr>
               
                <th style="width: 30%">Representante Legal:</th>
                <td><?php
                    echo $this->formulario->getElement(Application_Form_Proveedores::E_REPRESENTANTE)->renderViewHelper(),
                         $this->formulario->getElement(Application_Form_Proveedores::E_REPRESENTANTE)->renderDescription(),
                         $this->formulario->getElement(Application_Form_Proveedores::E_REPRESENTANTE)->renderErrors();
                    ?>
                </td>
                <th>Teléfono:</th><br>
                <td><?php
                    echo $this->formulario->getElement(Application_Form_Proveedores::E_TELEFONO)->renderViewHelper(),
                         $this->formulario->getElement(Application_Form_Proveedores::E_TELEFONO)->renderDescription(),
                         $this->formulario->getElement(Application_Form_Proveedores::E_TELEFONO)->renderErrors();
                         ?>
                </td>  
                
            </tr>
   

            <tr>
                  <th style="width: 14.5%">Dirección:</th>
                <td><?php
                    echo $this->formulario->getElement(Application_Form_Proveedores::E_DIRECCION)->renderViewHelper(),
                         $this->formulario->getElement(Application_Form_Proveedores::E_DIRECCION)->renderDescription(),
                         $this->formulario->getElement(Application_Form_Proveedores::E_DIRECCION)->renderErrors();
                    ?>
                </td>
                
                <th>Correo:</th>
                <td><?php
                    echo $this->formulario->getElement(Application_Form_Proveedores::E_CORREO)->renderViewHelper(),
                         $this->formulario->getElement(Application_Form_Proveedores::E_CORREO)->renderDescription(),
                         $this->formulario->getElement(Application_Form_Proveedores::E_CORREO)->renderErrors();
                             ?>
                </td>
                            
            
            </tr>
        </tbody>
    </table>
    <br>
  <!--  <table class="general" summary="Datos Del Proveedor" style="width:55%">
        <tbody>
            <tr>
                <th style="width: 14.5%">Dirección:</th>
                <td><?php
                    echo $this->formulario->getElement(Application_Form_Proveedores::E_DIRECCION)->renderViewHelper(),
                         $this->formulario->getElement(Application_Form_Proveedores::E_DIRECCION)->renderDescription(),
                         $this->formulario->getElement(Application_Form_Proveedores::E_DIRECCION)->renderErrors();
                    ?>
                </td>
            </tr>
        </tbody>  
    </table> --> 
    <br>
    <br>
</fieldset>   
<br><br>


 <!-- DATOS BANCARIOS PROVEEDORES -->   
 
<fieldset>             
    <table class="general" summary="Datos Bancarios de Proveedores" style="width:55%" id="tblProveedores">
        <legend style="font-size: 15px; margin-bottom: 0px;margin-left: 8px ;width: auto;">Datos Bancarios de Proveedores</legend>
        <tbody>  
            <tr>
                <th style="width: 20%">Entidad Bancaria</th><br>
                <td><?php
                    echo $this->formulario->getElement(Application_Form_Proveedores::E_COD)->renderViewHelper(),
                         $this->formulario->getElement(Application_Form_Proveedores::E_COD)->renderDescription(),
                         $this->formulario->getElement(Application_Form_Proveedores::E_COD)->renderErrors();
                         ?>
                </td>             
                <th style="width: 20%">Tipo de Cuenta</th>
                <td><?php
                    echo $this->formulario->getElement(Application_Form_Proveedores::E_TIPOCUENTA)->renderViewHelper(),
                         $this->formulario->getElement(Application_Form_Proveedores::E_TIPOCUENTA)->renderDescription(),
                         $this->formulario->getElement(Application_Form_Proveedores::E_TIPOCUENTA)->renderErrors();
                             ?>
                </td>
            </tr>
        </tbody>
    </table>

 
 <!-- DATOS BANCARIOS DE PROVEEDOR EN TABLA  -->
 
    <table class="general" summary="Datos Bancarios de Proveedores en tabla" style="width:55%">
        <tbody>  
            <tr>
                <th>Cod.</th><br>
                <th>Banco</th>
                <th>BCV</th>
                <th>Numero de Cuenta</th>
                <th style="width: 10%">Cuenta Activa</th>
            </tr>
            <tr>
                <td style="width: 10%"><?php 
                    echo $this->formulario->getElement(Application_Form_Proveedores::E_CODTXT)->renderViewHelper(),
                         $this->formulario->getElement(Application_Form_Proveedores::E_CODTXT)->renderDescription(),
                         $this->formulario->getElement(Application_Form_Proveedores::E_CODTXT)->renderErrors(); 
                         ?>
                </td>
                <td style="width: 10%"><?php
                    echo $this->formulario->getElement(Application_Form_Proveedores::E_BANCO)->renderViewHelper(),
                         $this->formulario->getElement(Application_Form_Proveedores::E_BANCO)->renderDescription(),
                         $this->formulario->getElement(Application_Form_Proveedores::E_BANCO)->renderErrors();
                             ?>
                </td>
                
                <td style="width: 10%"><?php
                    echo $this->formulario->getElement(Application_Form_Proveedores::E_BCV)->renderViewHelper(),
                         $this->formulario->getElement(Application_Form_Proveedores::E_BCV)->renderDescription(),
                         $this->formulario->getElement(Application_Form_Proveedores::E_BCV)->renderErrors();
                             ?>
                </td>
                <td style="width: 10%"><?php
                    echo $this->formulario->getElement(Application_Form_Proveedores::E_NUMCUENTA)->renderViewHelper(),
                         $this->formulario->getElement(Application_Form_Proveedores::E_NUMCUENTA)->renderDescription(),
                         $this->formulario->getElement(Application_Form_Proveedores::E_NUMCUENTA)->renderErrors();
                             ?>
                </td>  
                <?php echo $this->formulario->getElement(Application_Form_Proveedores::E_FECHA);?>
                
                <td align="center"><?php
                    echo $this->formulario->getElement(Application_Form_Proveedores::E_ACTIVA)->renderViewHelper(),
                         $this->formulario->getElement(Application_Form_Proveedores::E_ACTIVA)->renderDescription(),
                         $this->formulario->getElement(Application_Form_Proveedores::E_ACTIVA)->renderErrors();
                             ?>
                </td>
            </tr>
    
        </tbody>
    </table><br><br>
     <!-- BOTONES DE GUARDADO Y CANCELAR -->
    <table style="width: 99%;">
        <tbody>  
            <tr>
                <td style="text-align: right; "><?php
                   echo $this->formulario->getElement(Application_Form_Proveedores::E_CANCELAR)->renderViewHelper(); 
                    ?>
                </td>
                <td><?php
                    echo $this->formulario->getElement(Application_Form_Proveedores::E_GUARDAR)->renderViewHelper();
                    ?>
                </td>
            </tr>
        </tbody>  
    </table><br><br>
</fieldset>
 <br>
 <br>

 
 
 
<?php echo '</form>', PHP_EOL; ?>

 
