<style>
    th {
        text-align: center;
    }
</style>
<br>
<h1 style="text-align: center">LISTADO DE CUENTAS DÉBITO</h1>    

<fieldset><br>
    <table class="general" summary="Listado de Cuentas Débito">
    <legend style="font-size: 15px; margin-bottom: 0px;margin-left: 8px ;width: auto;">Listado de Cuentas Débito</legend>
        <thead>
            <tr>
                <th width="10%">R.I.F</th>
                <th>Razon Social</th>
                <th>Banco</th>
                <th>Tipo de Cuenta</th>
                <th>Numero de Cuenta</th>
                <th>Fecha</th>
                <th width="10%" colspan="2">Acción</th>
            </tr>
        </thead>
    <tbody>
<?php

if ($this->cuentas and $this->cuentas->count()):
    foreach ($this->cuentas as $fila): ?>
        <tr>
           
            <td align="center"><?php echo $fila->rif; ?></td>
            <td align="center"><?php echo $fila->razon; ?></td>
            <td align="center"><?php echo $fila->banco; ?></td>
            <td align="center"><?php echo $fila->tipocuenta; ?></td>
            <td align="center"><?php echo $fila->numcuenta; ?></td>
            <td align="center"><?php echo Fmo_Util::stringToZendDate($fila->fecha)->get('dd/MM/yyyy'); ?></td>
            
            <td width="5%" align="center"><a href="<?php echo $this->url(array('action' => 'editar', 'numcuenta' => $fila->numcuenta)); ?>" title="Editar"><?php echo $this->img('ico_editar.png'); ?></a></td>
            <td width="5%" align="center"><a href="<?php echo $this->url(array('action' => 'eliminar', 'numcuenta' => $fila->numcuenta)); ?>" title="Eliminar"><?php echo $this->img('ico_eliminar.png'); ?></a></td>
        </tr>
    <?php
        endforeach;
    else: ?>
            <tr>
                <td colspan="10" align="center">La consulta no devolvió registros</td>
            </tr>
    <?php
    endif; ?>
        </tbody>
    </table>
    <?php
    if ($this->cuentas):
       //Zend_Debug::dd($clientes);
        echo $this->paginationControl($this->cuentas);
    endif;
    ?>
 </fieldset>
 <br>
 <br>
