<br>
<br>
<h1 style="text-align: center">ELIMINAR TIPO DE CUENTA</h1>     

<br><br>
<fieldset>    
    <legend style="font-size: 15px; margin-bottom: -10px;margin-left: 8px ;width: auto;">Eliminar Tipo de Cuenta</legend>
    <br><br>
    <table class="general" summary="Proveedores" style="width:30%">
    <caption>¿Seguro que desea eliminar?</caption>
    <tbody>
    <tr>
        <th align="center" width="30%">ID:</th>
        <td align="center"><?php echo $this->escape($this->tipocuenta->id_tipo); ?></td>
    </tr>
    <tr>
        <th align="center">Tipo de Cuenta:</th>
        <td align="center"><?php echo $this->escape($this->tipocuenta->tipo); ?></td>
    </tr>
    <tr>
        <th align="center">Nombre:</th>
        <td align="center"><?php echo $this->escape($this->tipocuenta->nombre); ?></td>
    </tr>
    </table>
    <p align="center">
        <a class="button" href="<?php echo $this->url(array('module' => 'default', 'controller' => 'tipocuenta', 'action' => 'listar', 'page' => $this->page), null, true); ?>"><?php echo $this->img('ico_volver.png'); ?> Volver</a>
        <a class="button" href="<?php echo $this->url(array('module' => 'default', 'controller' => 'tipocuenta', 'action' => 'eliminar', 'confirmar' => 'S', 'page' => $this->page, 'id_tipo' => $this->tipocuenta->id_tipo), null, true); ?>"><?php echo $this->img('ico_eliminar.png'); ?> Eliminar</a>
    </p>
</fieldset>