<br>
<br>
<h1 style="text-align: center">REGISTRO DE NUEVO TIPO DE CUENTA</h1>

<!-- FORMULARIO DE REGISTRO DE CUENTAS FMO -->

<?php echo $this->formulario->renderForm(false); ?>

<fieldset><br>             
    <table class="general" summary="Tipo de Cuenta" style="width:38%">
       <legend style="font-size: 15px; margin-bottom: 0px;margin-left: 8px ;width: auto;">Nuevo Tipo de Cuenta</legend>
        <tbody>  
            <tr>
                <th>Tipo de Cuenta</th>
                <td><?php
                    echo $this->formulario->getElement(Application_Form_TipoCuenta::E_TIPO)->renderViewHelper(),
                         $this->formulario->getElement(Application_Form_TipoCuenta::E_TIPO)->renderDescription(),
                         $this->formulario->getElement(Application_Form_TipoCuenta::E_TIPO)->renderErrors();
                             ?>
                </td>
            </tr>
            <tr>
                <th>Nombre</th>
                <td><?php
                    echo $this->formulario->getElement(Application_Form_TipoCuenta::E_NOMBRE)->renderViewHelper(),
                         $this->formulario->getElement(Application_Form_TipoCuenta::E_NOMBRE)->renderDescription(),
                         $this->formulario->getElement(Application_Form_TipoCuenta::E_NOMBRE)->renderErrors();
                             ?>
                </td>
            </tr>
        </tbody>
    </table>
    <br>  
    <br>  
</fieldset><br><br><br><br>   


 <!-- BOTONES DE GUARDAR Y CANCELAR -->
 
    <table style="width: 99%;">
        <tbody>  
            <tr>
                <td style="text-align: right; "><?php
                   echo $this->formulario->getElement(Application_Form_TipoCuenta::E_CANCELAR)->renderViewHelper();
                    ?>
                </td>
                <td><?php
                    echo $this->formulario->getElement(Application_Form_TipoCuenta::E_GUARDAR)->renderViewHelper();
                    ?>
                </td>
            </tr>
        </tbody>  
    </table>
</div>

<?php echo '</form>', PHP_EOL; ?>


