<br>
<br>
<h1 style="text-align: center">REGISTRO ENTIDADES BANCARIAS</h1>

<!-- FORMULARIO DE REGISTRO DE CUENTAS FMO -->

<?php echo $this->formulario->renderForm(false); ?>

<fieldset><br>             
    <table class="general" summary="Codigo banco" style="width:70%">
       <legend style="font-size: 15px; margin-bottom: 0px;margin-left: 8px ;width: auto;">Nueva Entidad Bancaria</legend>
        <tbody>  
            <tr>
                <th style="width: 20%">Entidad Bancaria</th>
                <td><?php
                    echo $this->formulario->getElement(Application_Form_EntidadesBancarias::E_COD)->renderViewHelper(),
                         $this->formulario->getElement(Application_Form_EntidadesBancarias::E_COD)->renderDescription(),
                         $this->formulario->getElement(Application_Form_EntidadesBancarias::E_COD)->renderErrors();
                             ?>
                </td>
                <th style="width: 20%">Nombre del Banco:</th>
                <td><?php
                    echo $this->formulario->getElement(Application_Form_EntidadesBancarias::E_BANCO)->renderViewHelper(),
                         $this->formulario->getElement(Application_Form_EntidadesBancarias::E_BANCO)->renderDescription(),
                         $this->formulario->getElement(Application_Form_EntidadesBancarias::E_BANCO)->renderErrors();
                    ?>
                </td>
            </tr>
        </tbody>
    </table>
    <br>
    <table class="general" summary="Codigo BCV" style="width:70%">
        <tbody>
            <tr>
                <th style="width: 20%">Código BCV:</th>
                <td><?php
                    echo $this->formulario->getElement(Application_Form_EntidadesBancarias::E_BCV)->renderViewHelper(),
                         $this->formulario->getElement(Application_Form_EntidadesBancarias::E_BCV)->renderDescription(),
                         $this->formulario->getElement(Application_Form_EntidadesBancarias::E_BCV)->renderErrors();
                    ?>
                </td>
                <th style="width: 20%">Código Swift:</th>
                <td><?php
                    echo $this->formulario->getElement(Application_Form_EntidadesBancarias::E_SWIFT)->renderViewHelper(),
                         $this->formulario->getElement(Application_Form_EntidadesBancarias::E_SWIFT)->renderDescription(),
                         $this->formulario->getElement(Application_Form_EntidadesBancarias::E_SWIFT)->renderErrors();
                    ?>
                </td>
            </tr>
        </tbody>
    </table>
    <br>  
    <br>
    <table class="general" summary="Monto Maximo" style="width:20%">
        <tbody>
            <tr>
                <th style="width: 50%">Monto Maximo:</th>
                <td align="center">
                    <?php
                    echo $this->formulario->getElement(Application_Form_EntidadesBancarias::E_MONTO)->renderViewHelper(),
                         $this->formulario->getElement(Application_Form_EntidadesBancarias::E_MONTO)->renderDescription(),
                         $this->formulario->getElement(Application_Form_EntidadesBancarias::E_MONTO)->renderErrors();
                    ?>
                </td>
            </tr>
        </tbody>
    </table>
    <br>
</fieldset><br><br><br><br>   


 <!-- BOTONES DE GUARDAR Y CANCELAR -->
 
    <table style="width: 99%;">
        <tbody>  
            <tr>
                <td style="text-align: right; "><?php
                    echo $this->formulario->getElement(Application_Form_EntidadesBancarias::E_CANCELAR)->renderViewHelper();
                    ?>
                </td>
                <td><?php
                    echo $this->formulario->getElement(Application_Form_EntidadesBancarias::E_GUARDAR)->renderViewHelper();
                    ?>
                </td>
            </tr>
        </tbody>  
    </table>
</div>

<?php echo '</form>', PHP_EOL; ?>


