<style>
.h1, .h2, .h3, h1, h2, h3 {
    margin-top: 20px;
    margin-bottom: 10px;
}

.h1, .h2, .h3, .h4, .h5, .h6, h1, h2, h3, h4, h5, h6 {
    font-family: inherit;
    font-weight: 500;
    line-height: 1.1;
    color: #333;
}

h3 {
    display: block;
    font-size: 24px;
    margin-block-start: 1em;
    margin-block-end: 1em;
    margin-inline-start: 0px;
    margin-inline-end: 0px;
}
</style>

<h3 style="text-align: center">CARGAR HOJA DE CÁLCULO</h3>

<?php echo $this->formulario->renderForm(false); ?>


 <!-- ENDITADES BANCARIAS -->   
<fieldset>             
    <table class="general" summary="Información de Interfaz " style="width:30%">
        <legend style="font-size: 15px; margin-bottom: 0px;margin-left: 8px ;width: auto;">DATOS DE INTERFAZ</legend>
        <tbody>  
            <tr>
                
                <th>Entidad Bancaria</th><br>
                <td style="width: 5%"><?php
                    echo $this->formulario->getElement(Application_Form_Excel::E_COD)->renderViewHelper(),
                         $this->formulario->getElement(Application_Form_Excel::E_COD)->renderDescription(),
                         $this->formulario->getElement(Application_Form_Excel::E_COD)->renderErrors();
                         ?>
                </td>
                          
            </tr>
            
            <tr>
                <th>Tipo de Cliente:</th>
                <td><?php echo $this->formulario->getElement(Application_Form_Excel::E_CLIENTE)->renderViewHelper(),
                         $this->formulario->getElement(Application_Form_Excel::E_CLIENTE)->renderDescription(),
                         $this->formulario->getElement(Application_Form_Excel::E_CLIENTE)->renderErrors();
                         ?></td>
            </tr>
            
            <tr>
                 <th style="width: 40%">Titulo de la Interfaz</th>
                 <td><?php 
                    echo $this->formulario->getElement(Application_Form_Excel::E_TITULO)->renderViewHelper(),
                         $this->formulario->getElement(Application_Form_Excel::E_TITULO)->renderDescription(),
                         $this->formulario->getElement(Application_Form_Excel::E_TITULO)->renderErrors(); 
                         ?>
                 </td>
                 <?php echo $this->formulario->getElement(Application_Form_Excel::E_FECHA)->renderViewHelper();?>
                 
             </tr>
        </tbody>
    </table>
    <br>
</fieldset><br>
    <!-- DATOS DE INTERFAZ -->  
<fieldset><br>
    <legend style="font-size: 15px; margin-bottom: 0px;margin-left: 8px ;width: auto;">HOJA DE CÁLCULO</legend>

    <!-- <table class="general" align="center" summary="Formato" style="width: 15%">
        <tbody>
            <tr>
                <th style="width: 60%">Formato Excel: </th>
                <td align="center">
                    <a href="<?php //echo $this->baseUrl('public/Formato excel.pdf'); ?>" target="_blank" title="Descargar Estructuras Hoja de Calculo"><?php echo $this->img('ico_archivo_pdf.png'); ?>
                </td>
            </tr>
        </tbody>
    </table>  
    <br> -->
    <table align="center" summary="Archivo" style="width: 25%">
        <thead>
        </thead>
        <tbody>
            <tr>
                <td ><?php echo $this->formulario->getElement(Application_Form_Excel::E_ARCHIVO);?></td>
            </tr>
        </tbody>
    </table>   
 <br>

 </fieldset>

 <!-- BOTONES DE GUARDAR Y CANCELAR -->
 <br>
 
 <table style="width: 99%;">
        <tbody>  
            <tr>
                <td style="text-align: right;" >
                    <?php
                    echo $this->formulario->getElement(Application_Form_Excel::E_CANCELAR)->renderViewHelper();
                    ?>
                </td>
                <td ><?php
                    echo $this->formulario->getElement(Application_Form_Excel::E_CARGAR)->renderViewHelper();
                    ?>
                </td>

            </tr>
        </tbody>  
    </table>
</div>

<?php echo '</form>', PHP_EOL; ?>

<script type="text/javascript">
    $("#cargarTip").click(function(event){
        if(!confirm ("Desea continuar?"))
           event.preventDefault();
    });
</script>


