<br>
<br>
<h1 style="text-align: center">EDITAR TIPO DE REGISTRO</h1>

<!-- FORMULARIO DE REGISTRO DE CUENTAS FMO -->

<?php echo $this->formulario->renderForm(false); ?>

<fieldset><br>             
    <table class="general" summary="Tipo de Registro" style="width:35%">
       <legend style="font-size: 15px; margin-bottom: 0px;margin-left: 8px ;width: auto;">  Tipo de Registro</legend>
        <tbody>  
            <tr>
                <th style="width: 50%">Nombre de Registro</th>
                <td><?php
                    echo $this->formulario->getElement(Application_Form_TipoRegistro::E_NOMBRE)->renderViewHelper(),
                         $this->formulario->getElement(Application_Form_TipoRegistro::E_NOMBRE)->renderDescription(),
                         $this->formulario->getElement(Application_Form_TipoRegistro::E_NOMBRE)->renderErrors();
                             ?>
                </td>
            </tr>
        </tbody>
    </table>
    <br>  
    <br>  
</fieldset><br><br><br><br>   


 <!-- BOTONES DE GUARDAR Y CANCELAR -->
 
    <table style="width: 99%;">
        <tbody>  
            <tr>
                <td style="text-align: right; "><?php
                    echo $this->formulario->getElement(Application_Form_TipoRegistro::E_CANCELAR)->renderViewHelper();
                    ?>
                </td>
                <td><?php
                    echo $this->formulario->getElement(Application_Form_TipoRegistro::E_GUARDAR)->renderViewHelper();
                    ?>
                </td>
            </tr>
        </tbody>  
    </table>
</div>

<?php echo '</form>', PHP_EOL; ?>


